
#if !defined(HH_ENUM)
#define HH_ENUM

enum HIHIGH_ZINDEX {
	ZINDEX_PARTS	=			55,
	ZINDEX_HERO	=				50,
	ZINDEX_PARALLAX	=			30,
	ZINDEX_ITEM_OBJECT =		40,
	ZINDEX_PATICLE =			25,
	ZINDEX_FLOW_BACKGROUND =	20,
	ZINDEX_SUB_BACKGROUND =		15,
	ZINDEX_FULL_BACKGROUND =	10
};

enum SPRITE_TYPE {
	SPRITE_TYPE_SUB_BACKGROUND	= 5,
	SPRITE_TYPE_FLOW_BACKGROUND	= 10,
	SPRITE_TYPE_FULL_BACKGROUND	= 15,
	SPRITE_TYPE_OBJECT =		20,
	SPRITE_TYPE_HERO =			30
};

enum BACKGROUND_TYPE {
	FULL=0, 
	FLOW,
	SUB
};

enum INTERACTION_OBJECT_TYPE {
	INTERACTION_OBJECT_TYPE_NON=0, 
	INTERACTION_OBJECT_TYPE_COIN,
	INTERACTION_OBJECT_TYPE_FOOTBAR,
	INTERACTION_OBJECT_TYPE_FAKE_FOOTBAR,
	INTERACTION_OBJECT_TYPE_SUPERITEM,
	INTERACTION_OBJECT_TYPE_FULLCOIN,
	INTERACTION_OBJECT_TYPE_TRAP,
	INTERACTION_OBJECT_TYPE_STARTJUMP,
	INTERACTION_OBJECT_TYPE_WEIGHT,
	INTERACTION_OBJECT_TYPE_MAGNET,
	INTERACTION_OBJECT_TYPE_SHIELD,
	INTERACTION_OBJECT_TYPE_STARFISH,
	INTERACTION_OBJECT_TYPE_DOUBLE,
};

enum HERO_STATUS_TYPE {
	HERO_STATUS_TYPE_DEFAULT=0,
	HERO_STATUS_TYPE_NOREACTION,
	HERO_STATUS_TYPE_JUMP, 
	HERO_STATUS_TYPE_FOOTBAR,
	HERO_STATUS_TYPE_SUPERITEM,
	HERO_STATUS_TYPE_FALL,
	HERO_STATUS_TYPE_DROP,
	HERO_STATUS_TYPE_STARTJUMP,
	HERO_STATUS_TYPE_TRAP,
	HERO_STATUS_TYPE_FULLCOIN,
	HERO_STATUS_TYPE_WEIGHT,
	HERO_STATUS_TYPE_MAGNET,
	HERO_STATUS_TYPE_SHIELD,
	HERO_STATUS_TYPE_STARFISH,
	HERO_STATUS_TYPE_DOUBLE,
	HERO_STATUS_TYPE_DIE,
};


enum HERO_TILT_TYPE {
	HERO_TILT_TYPE_LEFT=0, 
	HERO_TILT_TYPE_RIGHT,
	HERO_TILT_TYPE_CENTER
};


enum  SETTING_TYPE{
	SETTING_TYPE_YES=0, 
	SETTING_TYPE_NO
};

enum  ITEM_HAVE_TYPE{
	ITEM_HAVE_TYPE_YES=0, 
	ITEM_HAVE_TYPE_NO
};




enum  COIN_SIZE_TYPE {
	COIN_SIZE_TYPE_SMALL =		0,
	COIN_SIZE_TYPE_NORMAL =		1,
	COIN_SIZE_TYPE_BIG =		2
};

enum  GOLD_AMOUNT_TYPE {
	GOLD_AMOUNT_TYPE_SMALL =	1,
	GOLD_AMOUNT_TYPE_NORMAL =	2,
	GOLD_AMOUNT_TYPE_BIG =		3
};

enum  COIN_TYPE {
	COIN_TYPE_NORMAL =		0,
	COIN_TYPE_CIRCLE =		1,
	COIN_TYPE_PATROL =		2
};

enum TEST_TYPE {
	TEST_TYPE_TRAP_COIN =		0
};

enum PLACE_TYPE {
	PLACE_TYPE_ITEMFRAME_1 =		1000,
	PLACE_TYPE_ITEMFRAME_2 =		1001

};

enum LAYER_TYPE {
	LAYER_TYPE_GAMEPLAYSCENE_PARTS		=	4002,
	LAYER_TYPE_GAMEPLAYSCENE_CORE		=	4003
};


enum BUTTON_TEXT_ALIGN {
    BUTTON_TEXT_ALIGN_CENTER,BUTTON_TEXT_ALIGN_RIGHT
};


enum NETWORK_STATUS_TYPE{
	TYPE_NOT_CONNECTED = 	0,
	TYPE_WIFI =				1,
	TYPE_MOBILE =			2
};

namespace Facebook
{
	enum REQUEST_TYPE{
		LOGIN_REQUEST = 		0,
		FRIENDS_REQUEST =		1,
		LOGOUT_REQUEST = 		2,
		INVITE_REQUEST = 		3,
		SHARED_REQUEST = 		4,
		SETTING_LOGIN_REQUEST = 5,
		NONE =					999,
		SHARED_ERROR =			6,
		SHARED_CANCEL =			7
	};
}


enum GameState {
    GAMESCENE = 1,
    OTHERSCENE
};

#endif
